import ContextProvider from "@/context/store";
import "./globals.css";
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Todo list",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ContextProvider>{children}</ContextProvider>
      </body>
    </html>
  );
}
